FROM elixir:1.4.0

MAINTAINER Alan Gardner <alan@armoin.com>

ENV MIX_ENV prod

# Install hex
RUN /usr/local/bin/mix local.hex --force && \
    /usr/local/bin/mix local.rebar --force && \
    /usr/local/bin/mix hex.info

WORKDIR /app
COPY . .

RUN mix do deps.get, deps.compile, compile
RUN mix phoenix.digest

CMD ["bash"]
